Document: fluttercoin-qt
Title: Debian fluttercoin-qt Manual
Author: <insert document author here>
Abstract: This manual describes what fluttercoin-qt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fluttercoin-qt/fluttercoin-qt.sgml.gz

Format: postscript
Files: /usr/share/doc/fluttercoin-qt/fluttercoin-qt.ps.gz

Format: text
Files: /usr/share/doc/fluttercoin-qt/fluttercoin-qt.text.gz

Format: HTML
Index: /usr/share/doc/fluttercoin-qt/html/index.html
Files: /usr/share/doc/fluttercoin-qt/html/*.html
